### ISSUE TITLE
linux/arm/v7

### ISSUE THREAD

**Issue by bttfw** [RakSrinaNa/Twitch-Miner#14]
Arm support would be amazing if its not to hard and time consuming to do

Still thanks allot

**Comment by RakSrinaNa** [comment]
There's one built. I don't know if it works though, you'll have to try.

**Comment by bttfw** [comment]
I am failing at the 2 factor authentication right now but I think it will

**Comment by bttfw** [comment]
Have it running in portainer now had to just login into the container after starting once without './main.py' start it manually enter token and then all is good

Thanks allot for this

**Comment by RakSrinaNa** [comment]
Well yeah for the credentials it's not the easiest in docker.

What I personally did is create the cookie folder on my computer and then mounted that folder in docker.
