### ISSUE TITLE
Your browser unsupported 

### ISSUE THREAD

**Issue by Septan** [RakSrinaNa/Twitch-Miner#19]
I use to be able type in token though docker terminal. Now, I notice have to select a browser and login. How can get this work? I using a nas with this docker.

**Comment by RakSrinaNa** [comment]
If it asks for a browser then you'll have to do it outside docker to get the cookies file.

**Comment by Septan** [comment]
where would I put the cookie file ?

**Comment by RakSrinaNa** [comment]
Basically run the script on your own device normally to create the cookies and then copy it to the volume you mount in docker.

Otherwise you can try looking at the miner code and create the cookie file yourself.

**Comment by Septan** [comment]
Thank you, I got it working. I had run on windows before never had cookie file. I was running into issue, it seems be fix by the update was push 6 minutes ago.
